--- 
output_dir: public
asset_dirs: ["images"]
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_compact

resume: 
  contact:
    name: "M. Dave Auayan"
    role: "Front End Developer"
    tel: "+1 425 336 1393"
    email: "m@auayan.com"
    address:
      street-address: "100 Andover Pk. W."
      extended-address: "Suite 150"
      post-office-box: "#204"
      locality: "Tukwila"
      region: "Washington"
      postal-code: "98188"
      country-name: "United States"
    bio: |
      I am the designer and developer of [lib.rario.us](http://lib.rario.us), 
      a social web application that helps people share their library, reviewed 
      in 2005 on one of Wired.com. I have over 10 years experience in writing 
      HTML and CSS and over 5 years writing PHP and MySQL web applications.
  sections: 
  - title: "Areas of Expertise"
    type: "skills"
    subsections:

    - title: "Computer Software"
      skills:
      - "Adobe Photoshop, ImageReady, Illustrator"
      - "QuarkXPress"
      - "Macromedia Dreamweaver, Flash"
      - "Apache Webserver"
      - "Mac OS 9, 10; Windows 98, 2000, XP, Win7; Linux"

    - title: "Computer Languages"
      skills:
      - "PHP"
      - "MySQL"
      - "JavaScript - including jQuery and Prototype.js"
      - "HTML/XHTML - including Haml"
      - "CSS - including Sass"
      - "XML"

  - title: "Employment History"
    type: "experience"
    subsections: 

    - title: "Front End Developer"
      duration: 
        start : 2008-01-07T09:00:00.00-08:00
      company: "LuxuryRealEstate.com"
      url: http://www.luxuryrealestate.com
      address:
        street-address: "2110 Western Avenue"
        locality: "Seattle"
        region: "Washington"
        postal-code: "98121"
        country-name: "United States"
      achievements: 
      - "Wrote semantic markup for new and existing clients"
      - "Developed interactive elements for sites using JavaScript"
      - "Technology Used: XHTML, CSS, JavaScript, Ruby on Rails, PHP"
      summary: |
        We developed high end real estate websites for clients in the 
        upper echelons of the market.

    - title: "Web Producer"
      duration: 
        start : 2007-10-10T09:00:00.00-08:00
      company: "Wizards of the Coast"
      url: "http://wizards.com"
      address: 
        street-address: "1600 Lind Ave. SW"
        extended-street-address: "Ste. 400"
        locality: "Renton"
        region: "Washington"
        postal-code: "98057"
        country-name: "United States"
      achievements: 
      - "Update website content"
      - "Technology Used: XHTML, XML"
      summary: |
        I formatted articles written onsite during tournaments and 
        deployed them using a custom built CMS.

    - title: "Web Designer"
      duration:
        start : 2007-08-06T09:00:00.00-08:00
        end   : 2007-12-22T17:00:00.00-08:00
      company: "down2night.com"
      url: "http://down2night.com"
      address:
        street-address: "2101 4th Ave."
        extended-street-address: "Ste. 1050"
        locality: "Seattle"
        region: "Washington"
        postal-code: "98121"
        country-name: "United States"
      achievements:
      - "Maintain and update down2night.com"
      - "Design sales materials"
      - "Technology Used: PHP, HTML, CSS, JavaScript"
      summary: |
        I designed a co-branded site for Oracle's Open World conference 
        at http://oracle.down2night.com

    - title: "Graphic Artist"
      duration:
        start : 2007-07-31T09:00:00.00-08:00
        end   : 2006-07-31T17:00:00.00-08:00
      company: "Group Photographers Association"
      url: "http://groupphotographers.com"
      address:
        street-address: "10220 E. Sprague Ave."
        extended-street-address: "Main Floor"
        locality: "Spokane Valley"
        region: "Washington"
        postal-code: "99206"
        country-name: "United States"
      achievements:
      - "Design artwork and layouts for sales envelopes and other promotional material"
      - "Coordinate with clients on creating and updating promotional material"
      - "Technology Used: Photoshop, Pagemaker"
      summary: |
        I was responsible for the creation and management of sales envelopes 
        for a nationwide client base of photographers. Working within strict 
        deadlines, I managed my time to work with multiple clients simultaneously, 
        and output up to 30,000 sales envelopes in a day.

    - title: "Graphic Designer"
      duration:
        start : 2006-07-01T09:00:00.00-08:00
        end   : 2007-07-01T09:00:00.00-08:00
      company: "Washington Photo & Digital"
      url: "http://washingtonphoto.com"
      address:
        street-address: "100 S. Division St."
        locality: "Spokane"
        region: "Washington"
        postal-code: "99201"
        country-name: "United States"
      achievements:
      - "Scan, digitally enhance and print photos from various sources"
      - "Design artwork and layouts"
      - "Redesign and maintain http://washingtonphoto.com"
      - "Technology Used: Photoshop, PHP, HTML, CSS, JavaScript"
      summary: |
        I used Photoshop or the photo processors to get the best possible 
        photos from digital and analog sources. I provided designs for our 
        clients for promotional material: signage, booth posters, business 
        cards, vehicle artwork, and Powerpoint presentations for clients.

    - title: "Graphic Designer"
      duration:
        start : 2003-07-01T09:00:00.00-08:00
        end   : 2004-07-01T09:00:00.00-08:00
      company: "SCW Consulting"
      url: "http://www.scwconsult.com"
      address:
        street-address: "9116 E. Sprague Ave."
        extended-street-address: "#150"
        locality: "Spokane"
        region: "Washington"
        postal-code: "99206"
        country-name: "United States"
      achievements:
      - "Design and maintain websites from concept to completion for growing clientele base"
      - "Design user interfaces for custom web applications for clients and in-house"
      - "Technology Used: Photoshop, Visual Studio, HTML, CSS, JavaScript"
      summary: |
        I used Photoshops to provide mock-ups for approval from clients. 
        Once approved I would then convert the mock-ups to HTML/CSS templates 
        by hand, and used Visual Studio to deploy. I designed promotional 
        materials and business cards for the company using Illustrator.

    - title: "Graphic Designer"
      duration:
        start : 2002-12-01T09:00:00.00+10:00
        end   : 2003-04-15T17:00:00.00+10:00
      company: "IT&E"
      url: "http://www.ite.net"
      address:
        street-address: "122 W. Harmon Ind. Park"
        extended-street-address: "Suite 103"
        locality: "Tamuning"
        region: "Guam"
        postal-code: "96913"
        country-name: "United States"
      achievements:
      - "Design advertisements for print in various publications"
      - "Design promotional materials including large format banners and vehicle graphics"
      - "Design and prepare graphics for the web"
      - "Design graphics for television"
      - "Technology Used: Photoshop, Illustrator"
      summary: |
        I used Photoshop for the heavy graphic elements, and used Illustrator 
        for layout of the ads. The print ads were for use in anything from 
        high gloss publications to newsprint to web use.

    - title: "Graphic Artist II"
      duration:
        start : 2000-08-01T09:00:00.00+10:00
        end   : 2002-12-01T17:00:00.00+10:00
      company: "Guam Publications, Inc"
      url: "http://www.guampdn.com"
      address:
        street-address: "244 Archbishop FC Flores St."
        extended-street-address: "Suite 103"
        locality: "Hagåtña"
        region: "Guam"
        postal-code: "96910"
        country-name: "United States"
      achievements:
      - "Layout and design of advertisements for various clients"
      - "Preflight photos for print in various media formats"
      - "Design pages for publication on the web"
      - "Train graphic artists"
      - "Technology Used: Photoshop, Dreamweaver, HTML, CSS"
      summary: |
        I used primarily Multi-Ad creator to layout ads, Photoshop for any
        graphic work, all for placement in a QuarkXPress layout of the news 
        print. For in-house presentations, I used Powerpoint, with custom 
        graphics using Photoshop. I used Photoshop and Image Ready to 
        design banner ads for the website.

  - title: "Higher Education"
    type: "education"
    subsections: 
    - title: "University of Guam"
      url: "http://uog.edu"
      address:
        street-address: "UOG Station"
        locality: "Mangilao"
        region: "Guam"
        postal-code: "96923"
        country-name: "United States"
      duration: 
        start : 1998-09-01T09:00:00.00+10:00
        end   : 2000-12-01T09:00:00.00+10:00
      summary: |
        I majored in Mass Communication and took classes in Broadcasting, Design, Art, Photography

